/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MenuPermission = IDL.Variant({
  'galeri' : IDL.Null,
  'userManagement' : IDL.Null,
  'kategori' : IDL.Null,
  'dokumen' : IDL.Null,
  'statistik' : IDL.Null,
  'berita' : IDL.Null,
  'tentang' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AdminUser = IDL.Record({
  'principal' : IDL.Text,
  'grantedMenus' : IDL.Vec(MenuPermission),
  'nama' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'addedAt' : Timestamp,
  'addedBy' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ArtikelInput = IDL.Record({
  'status' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'ringkasan' : IDL.Text,
  'gambar' : IDL.Opt(ExternalBlob),
  'judul' : IDL.Text,
  'author' : IDL.Text,
  'tanggalPublikasi' : IDL.Opt(IDL.Int),
  'konten' : IDL.Text,
});
export const ArtikelId = IDL.Nat;
export const Artikel = IDL.Record({
  'id' : ArtikelId,
  'status' : IDL.Text,
  'tanggal' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'ringkasan' : IDL.Text,
  'gambar' : IDL.Opt(ExternalBlob),
  'judul' : IDL.Text,
  'author' : IDL.Text,
  'tanggalPublikasi' : IDL.Int,
  'konten' : IDL.Text,
});
export const KategoriId = IDL.Nat;
export const StatusDokumen = IDL.Variant({
  'Berlaku' : IDL.Null,
  'Dicabut' : IDL.Null,
  'TidakBerlaku' : IDL.Null,
});
export const WorkflowStatus = IDL.Variant({
  'PendingReview' : IDL.Null,
  'Draft' : IDL.Null,
  'Published' : IDL.Null,
});
export const DokumenInput = IDL.Record({
  'tag' : IDL.Vec(IDL.Text),
  'kategoriId' : KategoriId,
  'status' : StatusDokumen,
  'tahun' : IDL.Nat,
  'judul' : IDL.Text,
  'relasiHukum' : IDL.Opt(IDL.Text),
  'abstrak' : IDL.Text,
  'tanggalPenetapan' : IDL.Text,
  'nomor' : IDL.Text,
  'tanggalPengundangan' : IDL.Opt(IDL.Int),
  'workflowStatus' : IDL.Opt(WorkflowStatus),
  'filePdf' : ExternalBlob,
});
export const DokumenId = IDL.Nat;
export const Dokumen = IDL.Record({
  'id' : DokumenId,
  'tag' : IDL.Vec(IDL.Text),
  'kategoriId' : KategoriId,
  'status' : StatusDokumen,
  'tahun' : IDL.Nat,
  'judul' : IDL.Text,
  'relasiHukum' : IDL.Opt(IDL.Text),
  'reviewedAt' : IDL.Opt(Timestamp),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'catatanKoreksi' : IDL.Text,
  'abstrak' : IDL.Text,
  'tanggalPenetapan' : IDL.Text,
  'nomor' : IDL.Text,
  'downloadCount' : IDL.Nat,
  'tanggalPengundangan' : IDL.Opt(IDL.Int),
  'workflowStatus' : WorkflowStatus,
  'filePdf' : ExternalBlob,
});
export const GaleriItemInput = IDL.Record({
  'album' : IDL.Text,
  'gambar' : IDL.Opt(ExternalBlob),
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
});
export const GaleriItemId = IDL.Nat;
export const GaleriItem = IDL.Record({
  'id' : GaleriItemId,
  'album' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'gambar' : IDL.Opt(ExternalBlob),
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
});
export const Kategori = IDL.Record({ 'id' : KategoriId, 'nama' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'performedAt' : Timestamp,
  'performedBy' : IDL.Text,
  'targetTitle' : IDL.Text,
  'targetType' : IDL.Text,
  'targetId' : IDL.Text,
});
export const MyPermissions = IDL.Record({
  'grantedMenus' : IDL.Vec(MenuPermission),
  'isAdmin' : IDL.Bool,
});
export const Statistik = IDL.Record({
  'totalArtikel' : IDL.Nat,
  'totalDokumen' : IDL.Nat,
  'perKategori' : IDL.Vec(IDL.Tuple(KategoriId, IDL.Text, IDL.Nat)),
  'totalUnduhan' : IDL.Nat,
});
export const TentangSlug = IDL.Variant({
  'visiMisi' : IDL.Null,
  'sejarah' : IDL.Null,
  'fungsi' : IDL.Null,
  'struktur' : IDL.Null,
  'dasarHukum' : IDL.Null,
});
export const TentangBlock = IDL.Variant({
  'daftarItem' : IDL.Vec(IDL.Text),
  'paragraf' : IDL.Text,
});
export const TentangContent = IDL.Record({ 'blocks' : IDL.Vec(TentangBlock) });
export const TentangPage = IDL.Record({
  'id' : IDL.Nat,
  'slug' : TentangSlug,
  'judul' : IDL.Text,
  'updatedAt' : Timestamp,
  'updatedBy' : IDL.Text,
  'konten' : TentangContent,
});
export const FilterDokumen = IDL.Record({
  'kategoriId' : IDL.Opt(KategoriId),
  'status' : IDL.Opt(StatusDokumen),
  'tahun' : IDL.Opt(IDL.Nat),
  'katakunci' : IDL.Opt(IDL.Text),
  'workflowStatus' : IDL.Opt(WorkflowStatus),
});
export const WorkflowResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const TentangPageInput = IDL.Record({
  'judul' : IDL.Text,
  'konten' : TentangContent,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAdminUser' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(MenuPermission)],
      [IDL.Variant({ 'ok' : AdminUser, 'err' : IDL.Text })],
      [],
    ),
  'addBerita' : IDL.Func([ArtikelInput], [Artikel], []),
  'addDokumen' : IDL.Func([DokumenInput], [Dokumen], []),
  'addGaleriItem' : IDL.Func([GaleriItemInput], [GaleriItem], []),
  'addKategori' : IDL.Func([IDL.Text], [Kategori], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBerita' : IDL.Func([ArtikelId], [IDL.Bool], []),
  'deleteDokumen' : IDL.Func([DokumenId], [IDL.Bool], []),
  'deleteGaleriItem' : IDL.Func([GaleriItemId], [IDL.Bool], []),
  'deleteKategori' : IDL.Func([KategoriId], [IDL.Bool], []),
  'downloadDokumen' : IDL.Func([DokumenId], [IDL.Bool], []),
  'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getBeritaDetail' : IDL.Func([ArtikelId], [IDL.Opt(Artikel)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDokumenDetail' : IDL.Func([DokumenId], [IDL.Opt(Dokumen)], ['query']),
  'getGaleriItem' : IDL.Func([GaleriItemId], [IDL.Opt(GaleriItem)], ['query']),
  'getMyPermissions' : IDL.Func([], [MyPermissions], ['query']),
  'getPendingReviewCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getStatistik' : IDL.Func([], [Statistik], ['query']),
  'getTentangPage' : IDL.Func([TentangSlug], [IDL.Opt(TentangPage)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdminUsers' : IDL.Func([], [IDL.Vec(AdminUser)], []),
  'listBerita' : IDL.Func([], [IDL.Vec(Artikel)], ['query']),
  'listDokumen' : IDL.Func([FilterDokumen], [IDL.Vec(Dokumen)], ['query']),
  'listDokumenAdmin' : IDL.Func([FilterDokumen], [IDL.Vec(Dokumen)], []),
  'listGaleri' : IDL.Func([], [IDL.Vec(GaleriItem)], ['query']),
  'listKategori' : IDL.Func([], [IDL.Vec(Kategori)], ['query']),
  'listTentangPages' : IDL.Func([], [IDL.Vec(TentangPage)], ['query']),
  'publishDokumen' : IDL.Func([DokumenId], [WorkflowResult], []),
  'removeAdminUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'returnToDraft' : IDL.Func([DokumenId, IDL.Text], [WorkflowResult], []),
  'submitForReview' : IDL.Func([DokumenId], [WorkflowResult], []),
  'updateAdminUser' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(MenuPermission), IDL.Bool],
      [IDL.Variant({ 'ok' : AdminUser, 'err' : IDL.Text })],
      [],
    ),
  'updateBerita' : IDL.Func([ArtikelId, ArtikelInput], [IDL.Opt(Artikel)], []),
  'updateDokumen' : IDL.Func([DokumenId, DokumenInput], [IDL.Opt(Dokumen)], []),
  'updateGaleriItem' : IDL.Func(
      [GaleriItemId, GaleriItemInput],
      [IDL.Opt(GaleriItem)],
      [],
    ),
  'updateKategori' : IDL.Func([KategoriId, IDL.Text], [IDL.Opt(Kategori)], []),
  'updateTentangPage' : IDL.Func(
      [TentangSlug, TentangPageInput],
      [IDL.Opt(TentangPage)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MenuPermission = IDL.Variant({
    'galeri' : IDL.Null,
    'userManagement' : IDL.Null,
    'kategori' : IDL.Null,
    'dokumen' : IDL.Null,
    'statistik' : IDL.Null,
    'berita' : IDL.Null,
    'tentang' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AdminUser = IDL.Record({
    'principal' : IDL.Text,
    'grantedMenus' : IDL.Vec(MenuPermission),
    'nama' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'addedAt' : Timestamp,
    'addedBy' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ArtikelInput = IDL.Record({
    'status' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'ringkasan' : IDL.Text,
    'gambar' : IDL.Opt(ExternalBlob),
    'judul' : IDL.Text,
    'author' : IDL.Text,
    'tanggalPublikasi' : IDL.Opt(IDL.Int),
    'konten' : IDL.Text,
  });
  const ArtikelId = IDL.Nat;
  const Artikel = IDL.Record({
    'id' : ArtikelId,
    'status' : IDL.Text,
    'tanggal' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'ringkasan' : IDL.Text,
    'gambar' : IDL.Opt(ExternalBlob),
    'judul' : IDL.Text,
    'author' : IDL.Text,
    'tanggalPublikasi' : IDL.Int,
    'konten' : IDL.Text,
  });
  const KategoriId = IDL.Nat;
  const StatusDokumen = IDL.Variant({
    'Berlaku' : IDL.Null,
    'Dicabut' : IDL.Null,
    'TidakBerlaku' : IDL.Null,
  });
  const WorkflowStatus = IDL.Variant({
    'PendingReview' : IDL.Null,
    'Draft' : IDL.Null,
    'Published' : IDL.Null,
  });
  const DokumenInput = IDL.Record({
    'tag' : IDL.Vec(IDL.Text),
    'kategoriId' : KategoriId,
    'status' : StatusDokumen,
    'tahun' : IDL.Nat,
    'judul' : IDL.Text,
    'relasiHukum' : IDL.Opt(IDL.Text),
    'abstrak' : IDL.Text,
    'tanggalPenetapan' : IDL.Text,
    'nomor' : IDL.Text,
    'tanggalPengundangan' : IDL.Opt(IDL.Int),
    'workflowStatus' : IDL.Opt(WorkflowStatus),
    'filePdf' : ExternalBlob,
  });
  const DokumenId = IDL.Nat;
  const Dokumen = IDL.Record({
    'id' : DokumenId,
    'tag' : IDL.Vec(IDL.Text),
    'kategoriId' : KategoriId,
    'status' : StatusDokumen,
    'tahun' : IDL.Nat,
    'judul' : IDL.Text,
    'relasiHukum' : IDL.Opt(IDL.Text),
    'reviewedAt' : IDL.Opt(Timestamp),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'catatanKoreksi' : IDL.Text,
    'abstrak' : IDL.Text,
    'tanggalPenetapan' : IDL.Text,
    'nomor' : IDL.Text,
    'downloadCount' : IDL.Nat,
    'tanggalPengundangan' : IDL.Opt(IDL.Int),
    'workflowStatus' : WorkflowStatus,
    'filePdf' : ExternalBlob,
  });
  const GaleriItemInput = IDL.Record({
    'album' : IDL.Text,
    'gambar' : IDL.Opt(ExternalBlob),
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
  });
  const GaleriItemId = IDL.Nat;
  const GaleriItem = IDL.Record({
    'id' : GaleriItemId,
    'album' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'gambar' : IDL.Opt(ExternalBlob),
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
  });
  const Kategori = IDL.Record({ 'id' : KategoriId, 'nama' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'performedAt' : Timestamp,
    'performedBy' : IDL.Text,
    'targetTitle' : IDL.Text,
    'targetType' : IDL.Text,
    'targetId' : IDL.Text,
  });
  const MyPermissions = IDL.Record({
    'grantedMenus' : IDL.Vec(MenuPermission),
    'isAdmin' : IDL.Bool,
  });
  const Statistik = IDL.Record({
    'totalArtikel' : IDL.Nat,
    'totalDokumen' : IDL.Nat,
    'perKategori' : IDL.Vec(IDL.Tuple(KategoriId, IDL.Text, IDL.Nat)),
    'totalUnduhan' : IDL.Nat,
  });
  const TentangSlug = IDL.Variant({
    'visiMisi' : IDL.Null,
    'sejarah' : IDL.Null,
    'fungsi' : IDL.Null,
    'struktur' : IDL.Null,
    'dasarHukum' : IDL.Null,
  });
  const TentangBlock = IDL.Variant({
    'daftarItem' : IDL.Vec(IDL.Text),
    'paragraf' : IDL.Text,
  });
  const TentangContent = IDL.Record({ 'blocks' : IDL.Vec(TentangBlock) });
  const TentangPage = IDL.Record({
    'id' : IDL.Nat,
    'slug' : TentangSlug,
    'judul' : IDL.Text,
    'updatedAt' : Timestamp,
    'updatedBy' : IDL.Text,
    'konten' : TentangContent,
  });
  const FilterDokumen = IDL.Record({
    'kategoriId' : IDL.Opt(KategoriId),
    'status' : IDL.Opt(StatusDokumen),
    'tahun' : IDL.Opt(IDL.Nat),
    'katakunci' : IDL.Opt(IDL.Text),
    'workflowStatus' : IDL.Opt(WorkflowStatus),
  });
  const WorkflowResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const TentangPageInput = IDL.Record({
    'judul' : IDL.Text,
    'konten' : TentangContent,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAdminUser' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(MenuPermission)],
        [IDL.Variant({ 'ok' : AdminUser, 'err' : IDL.Text })],
        [],
      ),
    'addBerita' : IDL.Func([ArtikelInput], [Artikel], []),
    'addDokumen' : IDL.Func([DokumenInput], [Dokumen], []),
    'addGaleriItem' : IDL.Func([GaleriItemInput], [GaleriItem], []),
    'addKategori' : IDL.Func([IDL.Text], [Kategori], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBerita' : IDL.Func([ArtikelId], [IDL.Bool], []),
    'deleteDokumen' : IDL.Func([DokumenId], [IDL.Bool], []),
    'deleteGaleriItem' : IDL.Func([GaleriItemId], [IDL.Bool], []),
    'deleteKategori' : IDL.Func([KategoriId], [IDL.Bool], []),
    'downloadDokumen' : IDL.Func([DokumenId], [IDL.Bool], []),
    'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getBeritaDetail' : IDL.Func([ArtikelId], [IDL.Opt(Artikel)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDokumenDetail' : IDL.Func([DokumenId], [IDL.Opt(Dokumen)], ['query']),
    'getGaleriItem' : IDL.Func(
        [GaleriItemId],
        [IDL.Opt(GaleriItem)],
        ['query'],
      ),
    'getMyPermissions' : IDL.Func([], [MyPermissions], ['query']),
    'getPendingReviewCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getStatistik' : IDL.Func([], [Statistik], ['query']),
    'getTentangPage' : IDL.Func(
        [TentangSlug],
        [IDL.Opt(TentangPage)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdminUsers' : IDL.Func([], [IDL.Vec(AdminUser)], []),
    'listBerita' : IDL.Func([], [IDL.Vec(Artikel)], ['query']),
    'listDokumen' : IDL.Func([FilterDokumen], [IDL.Vec(Dokumen)], ['query']),
    'listDokumenAdmin' : IDL.Func([FilterDokumen], [IDL.Vec(Dokumen)], []),
    'listGaleri' : IDL.Func([], [IDL.Vec(GaleriItem)], ['query']),
    'listKategori' : IDL.Func([], [IDL.Vec(Kategori)], ['query']),
    'listTentangPages' : IDL.Func([], [IDL.Vec(TentangPage)], ['query']),
    'publishDokumen' : IDL.Func([DokumenId], [WorkflowResult], []),
    'removeAdminUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'returnToDraft' : IDL.Func([DokumenId, IDL.Text], [WorkflowResult], []),
    'submitForReview' : IDL.Func([DokumenId], [WorkflowResult], []),
    'updateAdminUser' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(MenuPermission), IDL.Bool],
        [IDL.Variant({ 'ok' : AdminUser, 'err' : IDL.Text })],
        [],
      ),
    'updateBerita' : IDL.Func(
        [ArtikelId, ArtikelInput],
        [IDL.Opt(Artikel)],
        [],
      ),
    'updateDokumen' : IDL.Func(
        [DokumenId, DokumenInput],
        [IDL.Opt(Dokumen)],
        [],
      ),
    'updateGaleriItem' : IDL.Func(
        [GaleriItemId, GaleriItemInput],
        [IDL.Opt(GaleriItem)],
        [],
      ),
    'updateKategori' : IDL.Func(
        [KategoriId, IDL.Text],
        [IDL.Opt(Kategori)],
        [],
      ),
    'updateTentangPage' : IDL.Func(
        [TentangSlug, TentangPageInput],
        [IDL.Opt(TentangPage)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };